### ISSUE TITLE
Weighting issues

### ISSUE THREAD

**Issue by wanjianhui** [UARK-AICV/MEGANet#4]
Hello authors! During the training process, many weight files in different epochs will be generated. Which weight file of the epoch is used as the weight for the test? Since I didn't reproduce the results in the article when I reproduced, and the results in the article can be achieved by using the weight file you provided, I guess I used the wrong weight file.

**Comment by wuhuqifei0** [comment]
> Hello authors! During the training process, many weight files in different epochs will be generated. Which weight file of the epoch is used as the weight for the test? Since I didn't reproduce the results in the article when I reproduced, and the results in the article can be achieved by using the weight file you provided, I guess I used the wrong weight file.

Hello, may I ask if you were trained successfully? And could you share if you encountered any tensor mismatch issues?

**Comment by tanbuinhat** [comment]
Hi, sorry for our late response!

Thank you so much for your question! We simply use the final checkpoint for inference. We save multiple checkpoints at different epochs to continue training if there is an issue with the server. Regarding reproducing the results, we cannot guarantee 100% that the model will have the same results in different training runs because our model is deep learning-based. However, the results in different training runs should not vary significantly.
